[config]
default = "build"

[tasks.copy-vosk-libs]
description = "Copy Vosk dynamic library to target dirs"
script = [
  "mkdir -p target/debug",
  "mkdir -p target/release",
  "cp vosk/libvosk.* target/debug/",
  "cp vosk/libvosk.* target/release/"
]


[tasks.build]
description = "Compile the project (debug)"
command = "cargo"
args = ["build"]


[tasks.run]
description = "Run the binary"
dependencies  = ["build", "copy-vosk-libs"]
command = "cargo"
args    = ["run", "--bin", "markitup"]
